//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("test.Language.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About_us {
            get {
                return ResourceManager.GetString("About_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse More.
        /// </summary>
        public static string Browse_More {
            get {
                return ResourceManager.GetString("Browse_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Us.
        /// </summary>
        public static string Call_Us {
            get {
                return ResourceManager.GetString("Call_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborations.
        /// </summary>
        public static string Collaborations {
            get {
                return ResourceManager.GetString("Collaborations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string Company_Address {
            get {
                return ResourceManager.GetString("Company_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string Contact_Us {
            get {
                return ResourceManager.GetString("Contact_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Us.
        /// </summary>
        public static string Email_Us {
            get {
                return ResourceManager.GetString("Email_Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUTURE.
        /// </summary>
        public static string FUTURE {
            get {
                return ResourceManager.GetString("FUTURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HELP&amp;SUPPORT.
        /// </summary>
        public static string Help_Support {
            get {
                return ResourceManager.GetString("Help_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string Latest_News {
            get {
                return ResourceManager.GetString("Latest_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONGOING.
        /// </summary>
        public static string ONGOING {
            get {
                return ResourceManager.GetString("ONGOING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Collaborations.
        /// </summary>
        public static string Our_Collaborations {
            get {
                return ResourceManager.GetString("Our_Collaborations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Products.
        /// </summary>
        public static string Our_Products {
            get {
                return ResourceManager.GetString("Our_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Projects.
        /// </summary>
        public static string Our_Projects {
            get {
                return ResourceManager.GetString("Our_Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR SERVICES.
        /// </summary>
        public static string Our_Services {
            get {
                return ResourceManager.GetString("Our_Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAST.
        /// </summary>
        public static string PAST {
            get {
                return ResourceManager.GetString("PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK LINKS.
        /// </summary>
        public static string Quick_links {
            get {
                return ResourceManager.GetString("Quick_links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string Read_More {
            get {
                return ResourceManager.GetString("Read More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message.
        /// </summary>
        public static string Send_Message {
            get {
                return ResourceManager.GetString("Send_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message here.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send a message to us..
        /// </summary>
        public static string You_can {
            get {
                return ResourceManager.GetString("You_can", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your-Email.
        /// </summary>
        public static string Your_Email {
            get {
                return ResourceManager.GetString("Your_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Name.
        /// </summary>
        public static string Your_Name {
            get {
                return ResourceManager.GetString("Your_Name", resourceCulture);
            }
        }
    }
}
